name: gve_opening
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^2.3.0
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  community_material_icon: ^5.9.55
  crypto: ^3.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0
  freezed: ^0.14.2
  flash: ^2.0.1
  flutter_barcode_scanner: ^2.0.0
  flutter_bloc: ^7.3.0
  flutter_countdown_timer: ^4.1.0
  flutter_dotenv: ^5.0.2
  flutter_form_builder: ^6.1.0+1
  flutter_svg: ^0.22.0
  get_it: ^7.2.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  injectable: ^1.5.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  loading_overlay: ^0.3.0
  path_provider: ^2.0.2
  pin_code_fields: ^7.3.0
  platform_device_id: ^1.0.1
  rxdart: ^0.27.1
  shared_preferences: ^2.0.7
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.3
  injectable_generator: ^1.4.0
  json_serializable: ^4.1.1
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.4

flutter_native_splash:
  background_image: "assets/images/splash.png"
  fullscreen: true
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
